=== frankmu/babar-geode/babar-geode-kafka/src/main/resources/config/babar-rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/babar-rule"
	xmlns:tns="http://www.example.org/babar-rule"
	elementFormDefault="qualified">
	<element name="rule">
	    <complexType>
	    	<all>
				<element name="name" type="string"/>
				<element name="priority" type="integer"/>
				<element name="action" type="string"/>
				<element name="severity" type="integer"/>
				<element name="node-name" type="string"/>
				<element name="rule-type" type="string"/>
				<element name="match-pattern" type="string"/>
				<element name="variables">
					<complexType>
				 		<sequence>
				   			<element name="variable" type="string" maxOccurs="100"/>
				  		</sequence>
					</complexType>
				</element>
				<element name="fields">
					<complexType>
				 		<sequence>
				 			<element name="field" maxOccurs="100">
				            	<complexType>
							    	<simpleContent>
							    		<extension base="string">
							          		<attribute name="key" type="string" use="required"/>
							        	</extension>
							      	</simpleContent>
							    </complexType>
				            </element>
				  		</sequence>
					</complexType>
				</element>
	      	</all>
	    </complexType>
	</element>
</schema>

=== frankmu/babar-geode/babar-geode-kafka/src/main/resources/config/syslog_cisco_linkupdown.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns="http://www.example.org/babar-rule"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/babar-rule babar-rule.xsd ">
	<name>cisco-linkupdown</name>
	<priority>2</priority>
	<action>+</action>
	<severity>1</severity>
	<node-name>.*</node-name>
	<rule-type>cisco</rule-type>
	<timestamp-pattern>MMM  d HH:mm:ss</timestamp-pattern>
	<match-pattern>^(\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2})\s([^\s]*)\s\d+:\s\d+:\s\*?(\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2}[^\s]*): %LINK-3-UPDOWN: Interface ([0-9a-zA-Z\/]+),.*down$</match-pattern>
	<variables>
		<variable>timestamp</variable>
		<variable>hostname</variable>
		<variable>faulttime</variable>
		<variable>interfacename</variable>		
	</variables>
	<fields>
		<field key="timestamp">$timestamp</field>
		<field key="alertMsg">$hostname on the $interfacename is down at $faulttime</field>
		<field key="faultTime">$faulttime</field>
	</fields>
</rule>
